// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'entities/app_setting.dart';
import 'models/objectbox_models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5121943618149718626),
    name: 'AppSetting',
    lastPropertyId: const obx_int.IdUid(23, 841285738984438038),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8544777716972067089),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6609149107051581719),
        name: 'themeModeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6086591693586303361),
        name: 'language',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5434126743886115207),
        name: 'firstLaunch',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7122043611288802796),
        name: 'viewMode',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1653894918882835639),
        name: 'zoomMode',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6595456642154489478),
        name: 'autoHideControls',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7284823101350180005),
        name: 'enablePageTurnAnimation',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6487699937724156329),
        name: 'sourceLanguage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4528115815752419365),
        name: 'targetLanguage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7201055971686559902),
        name: 'translationEngine',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5568700854997839437),
        name: 'enableAutoTranslate',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 9215921051626568023),
        name: 'enableOCR',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6323566234640694917),
        name: 'fontStyle',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 6460389759490299214),
        name: 'fontSize',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 7757321739760803830),
        name: 'fontColor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 7858466590498988900),
        name: 'windowWidth',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 8954474870949502237),
        name: 'windowHeight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 2292100408921534885),
        name: 'isMaximized',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 8635266044315799464),
        name: 'lastOpenedFolder',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 6050820253688661451),
        name: 'recentFolders',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 4217673255680313976),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 841285738984438038),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8784750234000241707),
    name: 'Bookmark',
    lastPropertyId: const obx_int.IdUid(7, 3021923298438726624),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5113914932921392747),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6470031153726869157),
        name: 'mangaIdentifier',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 341285572432387781),
        name: 'pageNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3301490207579577636),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5774520203902247123),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8772475333759666051),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3021923298438726624),
        name: 'mangaId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 8130671117215934630),
        relationField: 'manga',
        relationTarget: 'Manga',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7058034151171372189),
    name: 'Manga',
    lastPropertyId: const obx_int.IdUid(12, 6095420927315160396),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8278036724748700015),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8985483381686398970),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8321710635427808202),
        name: 'coverPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7155778733213924033),
        name: 'folderPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6572057904544935906),
        name: 'totalPages',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 175547209066070243),
        name: 'currentPage',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1881701124556848404),
        name: 'readingProgress',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 921606892374930251),
        name: 'lastReadAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7337983334363815388),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1329602749707456127),
        name: 'isFavorite',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5743941790265839658),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6095420927315160396),
        name: 'author',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 8364437206894227957),
        name: 'bookmarks',
        targetId: const obx_int.IdUid(3, 8784750234000241707),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 5331440032858086137),
        name: 'translations',
        targetId: const obx_int.IdUid(6, 2415505355293907982),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 2618619786474531426),
        name: 'readingHistory',
        targetId: const obx_int.IdUid(5, 2756448151672386326),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 2756448151672386326),
    name: 'ReadingHistory',
    lastPropertyId: const obx_int.IdUid(6, 818331237378760767),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8707930245181151796),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2611542829699584718),
        name: 'mangaIdentifier',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4456972428266215033),
        name: 'pageNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8647009123097640214),
        name: 'readAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6519815077044873764),
        name: 'durationSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 818331237378760767),
        name: 'mangaId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 4543148024292211580),
        relationField: 'manga',
        relationTarget: 'Manga',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 2415505355293907982),
    name: 'TranslationCache',
    lastPropertyId: const obx_int.IdUid(10, 8227011584901208463),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 801436872509394733),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1373826601768737648),
        name: 'imageHash',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 7988622992771710728),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8334799019871557704),
        name: 'originalText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6943737333775904059),
        name: 'translatedText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5186240354197041117),
        name: 'sourceLang',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8062252942444290092),
        name: 'targetLang',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5810117990124171127),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2831495359634083190),
        name: 'lastAccessed',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1746520669864819281),
        name: 'accessCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8227011584901208463),
        name: 'mangaId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 8261290163231864429),
        relationField: 'manga',
        relationTarget: 'Manga',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 2415505355293907982),
    lastIndexId: const obx_int.IdUid(4, 8261290163231864429),
    lastRelationId: const obx_int.IdUid(3, 2618619786474531426),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [6478165685377947620],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      1719172900053681638,
      2023603410135870879,
      8851754687114307369,
      6595533291484219133,
      3038489842671152381,
      4067873473412644639,
      8888749971232529120,
      829177604148585166,
      3113603002852081707,
      13732998779524935,
      2525097297525193162,
      4522790813623098203,
      1192246530171958687,
      5171499852201327628,
      1261175636060091296,
      6323156185335673808,
      2684908818609253466,
      1479092931736306401,
      4931362880247410541,
      3572751485041049085,
      4927043005670380434,
      3870081841470964428,
      5086739206887230235,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AppSetting: obx_int.EntityDefinition<AppSetting>(
      model: _entities[0],
      toOneRelations: (AppSetting object) => [],
      toManyRelations: (AppSetting object) => {},
      getId: (AppSetting object) => object.id,
      setId: (AppSetting object, int id) {
        object.id = id;
      },
      objectToFB: (AppSetting object, fb.Builder fbb) {
        final languageOffset = fbb.writeString(object.language);
        final sourceLanguageOffset = fbb.writeString(object.sourceLanguage);
        final targetLanguageOffset = fbb.writeString(object.targetLanguage);
        final translationEngineOffset = fbb.writeString(
          object.translationEngine,
        );
        final fontColorOffset = fbb.writeString(object.fontColor);
        final lastOpenedFolderOffset = object.lastOpenedFolder == null
            ? null
            : fbb.writeString(object.lastOpenedFolder!);
        final recentFoldersOffset = fbb.writeList(
          object.recentFolders.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(24);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.themeModeIndex);
        fbb.addOffset(2, languageOffset);
        fbb.addBool(3, object.firstLaunch);
        fbb.addInt64(4, object.viewMode);
        fbb.addInt64(5, object.zoomMode);
        fbb.addBool(6, object.autoHideControls);
        fbb.addBool(7, object.enablePageTurnAnimation);
        fbb.addOffset(8, sourceLanguageOffset);
        fbb.addOffset(9, targetLanguageOffset);
        fbb.addOffset(10, translationEngineOffset);
        fbb.addBool(11, object.enableAutoTranslate);
        fbb.addBool(12, object.enableOCR);
        fbb.addInt64(13, object.fontStyle);
        fbb.addInt64(14, object.fontSize);
        fbb.addOffset(15, fontColorOffset);
        fbb.addFloat64(16, object.windowWidth);
        fbb.addFloat64(17, object.windowHeight);
        fbb.addBool(18, object.isMaximized);
        fbb.addOffset(19, lastOpenedFolderOffset);
        fbb.addOffset(20, recentFoldersOffset);
        fbb.addInt64(21, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(22, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = AppSetting(id: idParam)
          ..themeModeIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..language = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..firstLaunch = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            10,
            false,
          )
          ..viewMode = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..zoomMode = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..autoHideControls = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            16,
            false,
          )
          ..enablePageTurnAnimation = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            18,
            false,
          )
          ..sourceLanguage = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..targetLanguage = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 22, '')
          ..translationEngine = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 24, '')
          ..enableAutoTranslate = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            26,
            false,
          )
          ..enableOCR = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            28,
            false,
          )
          ..fontStyle = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            30,
            0,
          )
          ..fontSize = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            32,
            0,
          )
          ..fontColor = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 34, '')
          ..windowWidth = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            36,
            0,
          )
          ..windowHeight = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            38,
            0,
          )
          ..isMaximized = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            40,
            false,
          )
          ..lastOpenedFolder = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 42)
          ..recentFolders = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 44, [])
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 46, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 48, 0),
          );

        return object;
      },
    ),
    Bookmark: obx_int.EntityDefinition<Bookmark>(
      model: _entities[1],
      toOneRelations: (Bookmark object) => [object.manga],
      toManyRelations: (Bookmark object) => {},
      getId: (Bookmark object) => object.id,
      setId: (Bookmark object, int id) {
        object.id = id;
      },
      objectToFB: (Bookmark object, fb.Builder fbb) {
        final mangaIdentifierOffset = fbb.writeString(object.mangaIdentifier);
        final noteOffset = object.note == null
            ? null
            : fbb.writeString(object.note!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, mangaIdentifierOffset);
        fbb.addInt64(2, object.pageNumber);
        fbb.addOffset(3, noteOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.manga.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final mangaIdentifierParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pageNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object =
            Bookmark(
                mangaIdentifier: mangaIdentifierParam,
                pageNumber: pageNumberParam,
                note: noteParam,
                createdAt: createdAtParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..updatedAt = updatedAtValue == null
                  ? null
                  : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        object.manga.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.manga.attach(store);
        return object;
      },
    ),
    Manga: obx_int.EntityDefinition<Manga>(
      model: _entities[2],
      toOneRelations: (Manga object) => [],
      toManyRelations: (Manga object) => {
        obx_int.RelInfo<Manga>.toMany(1, object.id): object.bookmarks,
        obx_int.RelInfo<Manga>.toMany(2, object.id): object.translations,
        obx_int.RelInfo<Manga>.toMany(3, object.id): object.readingHistory,
      },
      getId: (Manga object) => object.id,
      setId: (Manga object, int id) {
        object.id = id;
      },
      objectToFB: (Manga object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final coverPathOffset = object.coverPath == null
            ? null
            : fbb.writeString(object.coverPath!);
        final folderPathOffset = object.folderPath == null
            ? null
            : fbb.writeString(object.folderPath!);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final authorOffset = object.author == null
            ? null
            : fbb.writeString(object.author!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, coverPathOffset);
        fbb.addOffset(3, folderPathOffset);
        fbb.addInt64(4, object.totalPages);
        fbb.addInt64(5, object.currentPage);
        fbb.addFloat64(6, object.readingProgress);
        fbb.addInt64(7, object.lastReadAt?.millisecondsSinceEpoch);
        fbb.addOffset(8, tagsOffset);
        fbb.addBool(9, object.isFavorite);
        fbb.addOffset(10, descriptionOffset);
        fbb.addOffset(11, authorOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastReadAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final coverPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final folderPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final totalPagesParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final currentPageParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final readingProgressParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final lastReadAtParam = lastReadAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastReadAtValue);
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 20, []);
        final isFavoriteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final authorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final object = Manga(
          title: titleParam,
          coverPath: coverPathParam,
          folderPath: folderPathParam,
          totalPages: totalPagesParam,
          currentPage: currentPageParam,
          readingProgress: readingProgressParam,
          lastReadAt: lastReadAtParam,
          tags: tagsParam,
          isFavorite: isFavoriteParam,
          description: descriptionParam,
          author: authorParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<Manga>(
          object.bookmarks,
          store,
          obx_int.RelInfo<Manga>.toMany(1, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<Manga>(
          object.translations,
          store,
          obx_int.RelInfo<Manga>.toMany(2, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<Manga>(
          object.readingHistory,
          store,
          obx_int.RelInfo<Manga>.toMany(3, object.id),
        );
        return object;
      },
    ),
    ReadingHistory: obx_int.EntityDefinition<ReadingHistory>(
      model: _entities[3],
      toOneRelations: (ReadingHistory object) => [object.manga],
      toManyRelations: (ReadingHistory object) => {},
      getId: (ReadingHistory object) => object.id,
      setId: (ReadingHistory object, int id) {
        object.id = id;
      },
      objectToFB: (ReadingHistory object, fb.Builder fbb) {
        final mangaIdentifierOffset = fbb.writeString(object.mangaIdentifier);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, mangaIdentifierOffset);
        fbb.addInt64(2, object.pageNumber);
        fbb.addInt64(3, object.readAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.durationSeconds);
        fbb.addInt64(5, object.manga.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final mangaIdentifierParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pageNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final durationSecondsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final readAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = ReadingHistory(
          mangaIdentifier: mangaIdentifierParam,
          pageNumber: pageNumberParam,
          durationSeconds: durationSecondsParam,
          readAt: readAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.manga.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.manga.attach(store);
        return object;
      },
    ),
    TranslationCache: obx_int.EntityDefinition<TranslationCache>(
      model: _entities[4],
      toOneRelations: (TranslationCache object) => [object.manga],
      toManyRelations: (TranslationCache object) => {},
      getId: (TranslationCache object) => object.id,
      setId: (TranslationCache object, int id) {
        object.id = id;
      },
      objectToFB: (TranslationCache object, fb.Builder fbb) {
        final imageHashOffset = fbb.writeString(object.imageHash);
        final originalTextOffset = fbb.writeString(object.originalText);
        final translatedTextOffset = fbb.writeString(object.translatedText);
        final sourceLangOffset = fbb.writeString(object.sourceLang);
        final targetLangOffset = fbb.writeString(object.targetLang);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, imageHashOffset);
        fbb.addOffset(2, originalTextOffset);
        fbb.addOffset(3, translatedTextOffset);
        fbb.addOffset(4, sourceLangOffset);
        fbb.addOffset(5, targetLangOffset);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.lastAccessed?.millisecondsSinceEpoch);
        fbb.addInt64(8, object.accessCount);
        fbb.addInt64(9, object.manga.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastAccessedValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final imageHashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final originalTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final translatedTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final sourceLangParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final targetLangParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object =
            TranslationCache(
                imageHash: imageHashParam,
                originalText: originalTextParam,
                translatedText: translatedTextParam,
                sourceLang: sourceLangParam,
                targetLang: targetLangParam,
                createdAt: createdAtParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..lastAccessed = lastAccessedValue == null
                  ? null
                  : DateTime.fromMillisecondsSinceEpoch(lastAccessedValue)
              ..accessCount = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                20,
                0,
              );
        object.manga.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        object.manga.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppSetting] entity fields to define ObjectBox queries.
class AppSetting_ {
  /// See [AppSetting.id].
  static final id = obx.QueryIntegerProperty<AppSetting>(
    _entities[0].properties[0],
  );

  /// See [AppSetting.themeModeIndex].
  static final themeModeIndex = obx.QueryIntegerProperty<AppSetting>(
    _entities[0].properties[1],
  );

  /// See [AppSetting.language].
  static final language = obx.QueryStringProperty<AppSetting>(
    _entities[0].properties[2],
  );

  /// See [AppSetting.firstLaunch].
  static final firstLaunch = obx.QueryBooleanProperty<AppSetting>(
    _entities[0].properties[3],
  );

  /// See [AppSetting.viewMode].
  static final viewMode = obx.QueryIntegerProperty<AppSetting>(
    _entities[0].properties[4],
  );

  /// See [AppSetting.zoomMode].
  static final zoomMode = obx.QueryIntegerProperty<AppSetting>(
    _entities[0].properties[5],
  );

  /// See [AppSetting.autoHideControls].
  static final autoHideControls = obx.QueryBooleanProperty<AppSetting>(
    _entities[0].properties[6],
  );

  /// See [AppSetting.enablePageTurnAnimation].
  static final enablePageTurnAnimation = obx.QueryBooleanProperty<AppSetting>(
    _entities[0].properties[7],
  );

  /// See [AppSetting.sourceLanguage].
  static final sourceLanguage = obx.QueryStringProperty<AppSetting>(
    _entities[0].properties[8],
  );

  /// See [AppSetting.targetLanguage].
  static final targetLanguage = obx.QueryStringProperty<AppSetting>(
    _entities[0].properties[9],
  );

  /// See [AppSetting.translationEngine].
  static final translationEngine = obx.QueryStringProperty<AppSetting>(
    _entities[0].properties[10],
  );

  /// See [AppSetting.enableAutoTranslate].
  static final enableAutoTranslate = obx.QueryBooleanProperty<AppSetting>(
    _entities[0].properties[11],
  );

  /// See [AppSetting.enableOCR].
  static final enableOCR = obx.QueryBooleanProperty<AppSetting>(
    _entities[0].properties[12],
  );

  /// See [AppSetting.fontStyle].
  static final fontStyle = obx.QueryIntegerProperty<AppSetting>(
    _entities[0].properties[13],
  );

  /// See [AppSetting.fontSize].
  static final fontSize = obx.QueryIntegerProperty<AppSetting>(
    _entities[0].properties[14],
  );

  /// See [AppSetting.fontColor].
  static final fontColor = obx.QueryStringProperty<AppSetting>(
    _entities[0].properties[15],
  );

  /// See [AppSetting.windowWidth].
  static final windowWidth = obx.QueryDoubleProperty<AppSetting>(
    _entities[0].properties[16],
  );

  /// See [AppSetting.windowHeight].
  static final windowHeight = obx.QueryDoubleProperty<AppSetting>(
    _entities[0].properties[17],
  );

  /// See [AppSetting.isMaximized].
  static final isMaximized = obx.QueryBooleanProperty<AppSetting>(
    _entities[0].properties[18],
  );

  /// See [AppSetting.lastOpenedFolder].
  static final lastOpenedFolder = obx.QueryStringProperty<AppSetting>(
    _entities[0].properties[19],
  );

  /// See [AppSetting.recentFolders].
  static final recentFolders = obx.QueryStringVectorProperty<AppSetting>(
    _entities[0].properties[20],
  );

  /// See [AppSetting.createdAt].
  static final createdAt = obx.QueryDateProperty<AppSetting>(
    _entities[0].properties[21],
  );

  /// See [AppSetting.updatedAt].
  static final updatedAt = obx.QueryDateProperty<AppSetting>(
    _entities[0].properties[22],
  );
}

/// [Bookmark] entity fields to define ObjectBox queries.
class Bookmark_ {
  /// See [Bookmark.id].
  static final id = obx.QueryIntegerProperty<Bookmark>(
    _entities[1].properties[0],
  );

  /// See [Bookmark.mangaIdentifier].
  static final mangaIdentifier = obx.QueryStringProperty<Bookmark>(
    _entities[1].properties[1],
  );

  /// See [Bookmark.pageNumber].
  static final pageNumber = obx.QueryIntegerProperty<Bookmark>(
    _entities[1].properties[2],
  );

  /// See [Bookmark.note].
  static final note = obx.QueryStringProperty<Bookmark>(
    _entities[1].properties[3],
  );

  /// See [Bookmark.createdAt].
  static final createdAt = obx.QueryDateProperty<Bookmark>(
    _entities[1].properties[4],
  );

  /// See [Bookmark.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Bookmark>(
    _entities[1].properties[5],
  );

  /// See [Bookmark.manga].
  static final manga = obx.QueryRelationToOne<Bookmark, Manga>(
    _entities[1].properties[6],
  );
}

/// [Manga] entity fields to define ObjectBox queries.
class Manga_ {
  /// See [Manga.id].
  static final id = obx.QueryIntegerProperty<Manga>(_entities[2].properties[0]);

  /// See [Manga.title].
  static final title = obx.QueryStringProperty<Manga>(
    _entities[2].properties[1],
  );

  /// See [Manga.coverPath].
  static final coverPath = obx.QueryStringProperty<Manga>(
    _entities[2].properties[2],
  );

  /// See [Manga.folderPath].
  static final folderPath = obx.QueryStringProperty<Manga>(
    _entities[2].properties[3],
  );

  /// See [Manga.totalPages].
  static final totalPages = obx.QueryIntegerProperty<Manga>(
    _entities[2].properties[4],
  );

  /// See [Manga.currentPage].
  static final currentPage = obx.QueryIntegerProperty<Manga>(
    _entities[2].properties[5],
  );

  /// See [Manga.readingProgress].
  static final readingProgress = obx.QueryDoubleProperty<Manga>(
    _entities[2].properties[6],
  );

  /// See [Manga.lastReadAt].
  static final lastReadAt = obx.QueryDateProperty<Manga>(
    _entities[2].properties[7],
  );

  /// See [Manga.tags].
  static final tags = obx.QueryStringVectorProperty<Manga>(
    _entities[2].properties[8],
  );

  /// See [Manga.isFavorite].
  static final isFavorite = obx.QueryBooleanProperty<Manga>(
    _entities[2].properties[9],
  );

  /// See [Manga.description].
  static final description = obx.QueryStringProperty<Manga>(
    _entities[2].properties[10],
  );

  /// See [Manga.author].
  static final author = obx.QueryStringProperty<Manga>(
    _entities[2].properties[11],
  );

  /// see [Manga.bookmarks]
  static final bookmarks = obx.QueryRelationToMany<Manga, Bookmark>(
    _entities[2].relations[0],
  );

  /// see [Manga.translations]
  static final translations = obx.QueryRelationToMany<Manga, TranslationCache>(
    _entities[2].relations[1],
  );

  /// see [Manga.readingHistory]
  static final readingHistory = obx.QueryRelationToMany<Manga, ReadingHistory>(
    _entities[2].relations[2],
  );
}

/// [ReadingHistory] entity fields to define ObjectBox queries.
class ReadingHistory_ {
  /// See [ReadingHistory.id].
  static final id = obx.QueryIntegerProperty<ReadingHistory>(
    _entities[3].properties[0],
  );

  /// See [ReadingHistory.mangaIdentifier].
  static final mangaIdentifier = obx.QueryStringProperty<ReadingHistory>(
    _entities[3].properties[1],
  );

  /// See [ReadingHistory.pageNumber].
  static final pageNumber = obx.QueryIntegerProperty<ReadingHistory>(
    _entities[3].properties[2],
  );

  /// See [ReadingHistory.readAt].
  static final readAt = obx.QueryDateProperty<ReadingHistory>(
    _entities[3].properties[3],
  );

  /// See [ReadingHistory.durationSeconds].
  static final durationSeconds = obx.QueryIntegerProperty<ReadingHistory>(
    _entities[3].properties[4],
  );

  /// See [ReadingHistory.manga].
  static final manga = obx.QueryRelationToOne<ReadingHistory, Manga>(
    _entities[3].properties[5],
  );
}

/// [TranslationCache] entity fields to define ObjectBox queries.
class TranslationCache_ {
  /// See [TranslationCache.id].
  static final id = obx.QueryIntegerProperty<TranslationCache>(
    _entities[4].properties[0],
  );

  /// See [TranslationCache.imageHash].
  static final imageHash = obx.QueryStringProperty<TranslationCache>(
    _entities[4].properties[1],
  );

  /// See [TranslationCache.originalText].
  static final originalText = obx.QueryStringProperty<TranslationCache>(
    _entities[4].properties[2],
  );

  /// See [TranslationCache.translatedText].
  static final translatedText = obx.QueryStringProperty<TranslationCache>(
    _entities[4].properties[3],
  );

  /// See [TranslationCache.sourceLang].
  static final sourceLang = obx.QueryStringProperty<TranslationCache>(
    _entities[4].properties[4],
  );

  /// See [TranslationCache.targetLang].
  static final targetLang = obx.QueryStringProperty<TranslationCache>(
    _entities[4].properties[5],
  );

  /// See [TranslationCache.createdAt].
  static final createdAt = obx.QueryDateProperty<TranslationCache>(
    _entities[4].properties[6],
  );

  /// See [TranslationCache.lastAccessed].
  static final lastAccessed = obx.QueryDateProperty<TranslationCache>(
    _entities[4].properties[7],
  );

  /// See [TranslationCache.accessCount].
  static final accessCount = obx.QueryIntegerProperty<TranslationCache>(
    _entities[4].properties[8],
  );

  /// See [TranslationCache.manga].
  static final manga = obx.QueryRelationToOne<TranslationCache, Manga>(
    _entities[4].properties[9],
  );
}
