// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'entities/app_setting.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5121943618149718626),
    name: 'AppSetting',
    lastPropertyId: const obx_int.IdUid(23, 841285738984438038),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8544777716972067089),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6609149107051581719),
        name: 'themeModeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6086591693586303361),
        name: 'language',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5434126743886115207),
        name: 'firstLaunch',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7122043611288802796),
        name: 'viewMode',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1653894918882835639),
        name: 'zoomMode',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6595456642154489478),
        name: 'autoHideControls',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7284823101350180005),
        name: 'enablePageTurnAnimation',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6487699937724156329),
        name: 'sourceLanguage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4528115815752419365),
        name: 'targetLanguage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7201055971686559902),
        name: 'translationEngine',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5568700854997839437),
        name: 'enableAutoTranslate',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 9215921051626568023),
        name: 'enableOCR',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6323566234640694917),
        name: 'fontStyle',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 6460389759490299214),
        name: 'fontSize',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 7757321739760803830),
        name: 'fontColor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 7858466590498988900),
        name: 'windowWidth',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 8954474870949502237),
        name: 'windowHeight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 2292100408921534885),
        name: 'isMaximized',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 8635266044315799464),
        name: 'lastOpenedFolder',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 6050820253688661451),
        name: 'recentFolders',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 4217673255680313976),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 841285738984438038),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 5121943618149718626),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [6478165685377947620],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      1719172900053681638,
      2023603410135870879,
      8851754687114307369,
      6595533291484219133,
      3038489842671152381,
      4067873473412644639,
      8888749971232529120,
      829177604148585166,
      3113603002852081707,
      13732998779524935,
      2525097297525193162,
      4522790813623098203,
      1192246530171958687,
      5171499852201327628,
      1261175636060091296,
      6323156185335673808,
      2684908818609253466,
      1479092931736306401,
      4931362880247410541,
      3572751485041049085,
      4927043005670380434,
      3870081841470964428,
      5086739206887230235,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AppSetting: obx_int.EntityDefinition<AppSetting>(
      model: _entities[0],
      toOneRelations: (AppSetting object) => [],
      toManyRelations: (AppSetting object) => {},
      getId: (AppSetting object) => object.id,
      setId: (AppSetting object, int id) {
        object.id = id;
      },
      objectToFB: (AppSetting object, fb.Builder fbb) {
        final languageOffset = fbb.writeString(object.language);
        final sourceLanguageOffset = fbb.writeString(object.sourceLanguage);
        final targetLanguageOffset = fbb.writeString(object.targetLanguage);
        final translationEngineOffset = fbb.writeString(
          object.translationEngine,
        );
        final fontColorOffset = fbb.writeString(object.fontColor);
        final lastOpenedFolderOffset = object.lastOpenedFolder == null
            ? null
            : fbb.writeString(object.lastOpenedFolder!);
        final recentFoldersOffset = fbb.writeList(
          object.recentFolders.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(24);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.themeModeIndex);
        fbb.addOffset(2, languageOffset);
        fbb.addBool(3, object.firstLaunch);
        fbb.addInt64(4, object.viewMode);
        fbb.addInt64(5, object.zoomMode);
        fbb.addBool(6, object.autoHideControls);
        fbb.addBool(7, object.enablePageTurnAnimation);
        fbb.addOffset(8, sourceLanguageOffset);
        fbb.addOffset(9, targetLanguageOffset);
        fbb.addOffset(10, translationEngineOffset);
        fbb.addBool(11, object.enableAutoTranslate);
        fbb.addBool(12, object.enableOCR);
        fbb.addInt64(13, object.fontStyle);
        fbb.addInt64(14, object.fontSize);
        fbb.addOffset(15, fontColorOffset);
        fbb.addFloat64(16, object.windowWidth);
        fbb.addFloat64(17, object.windowHeight);
        fbb.addBool(18, object.isMaximized);
        fbb.addOffset(19, lastOpenedFolderOffset);
        fbb.addOffset(20, recentFoldersOffset);
        fbb.addInt64(21, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(22, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = AppSetting(id: idParam)
          ..themeModeIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..language = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..firstLaunch = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            10,
            false,
          )
          ..viewMode = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..zoomMode = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..autoHideControls = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            16,
            false,
          )
          ..enablePageTurnAnimation = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            18,
            false,
          )
          ..sourceLanguage = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..targetLanguage = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 22, '')
          ..translationEngine = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 24, '')
          ..enableAutoTranslate = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            26,
            false,
          )
          ..enableOCR = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            28,
            false,
          )
          ..fontStyle = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            30,
            0,
          )
          ..fontSize = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            32,
            0,
          )
          ..fontColor = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 34, '')
          ..windowWidth = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            36,
            0,
          )
          ..windowHeight = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            38,
            0,
          )
          ..isMaximized = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            40,
            false,
          )
          ..lastOpenedFolder = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 42)
          ..recentFolders = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 44, [])
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 46, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 48, 0),
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppSetting] entity fields to define ObjectBox queries.
class AppSetting_ {
  /// See [AppSetting.id].
  static final id = obx.QueryIntegerProperty<AppSetting>(
    _entities[0].properties[0],
  );

  /// See [AppSetting.themeModeIndex].
  static final themeModeIndex = obx.QueryIntegerProperty<AppSetting>(
    _entities[0].properties[1],
  );

  /// See [AppSetting.language].
  static final language = obx.QueryStringProperty<AppSetting>(
    _entities[0].properties[2],
  );

  /// See [AppSetting.firstLaunch].
  static final firstLaunch = obx.QueryBooleanProperty<AppSetting>(
    _entities[0].properties[3],
  );

  /// See [AppSetting.viewMode].
  static final viewMode = obx.QueryIntegerProperty<AppSetting>(
    _entities[0].properties[4],
  );

  /// See [AppSetting.zoomMode].
  static final zoomMode = obx.QueryIntegerProperty<AppSetting>(
    _entities[0].properties[5],
  );

  /// See [AppSetting.autoHideControls].
  static final autoHideControls = obx.QueryBooleanProperty<AppSetting>(
    _entities[0].properties[6],
  );

  /// See [AppSetting.enablePageTurnAnimation].
  static final enablePageTurnAnimation = obx.QueryBooleanProperty<AppSetting>(
    _entities[0].properties[7],
  );

  /// See [AppSetting.sourceLanguage].
  static final sourceLanguage = obx.QueryStringProperty<AppSetting>(
    _entities[0].properties[8],
  );

  /// See [AppSetting.targetLanguage].
  static final targetLanguage = obx.QueryStringProperty<AppSetting>(
    _entities[0].properties[9],
  );

  /// See [AppSetting.translationEngine].
  static final translationEngine = obx.QueryStringProperty<AppSetting>(
    _entities[0].properties[10],
  );

  /// See [AppSetting.enableAutoTranslate].
  static final enableAutoTranslate = obx.QueryBooleanProperty<AppSetting>(
    _entities[0].properties[11],
  );

  /// See [AppSetting.enableOCR].
  static final enableOCR = obx.QueryBooleanProperty<AppSetting>(
    _entities[0].properties[12],
  );

  /// See [AppSetting.fontStyle].
  static final fontStyle = obx.QueryIntegerProperty<AppSetting>(
    _entities[0].properties[13],
  );

  /// See [AppSetting.fontSize].
  static final fontSize = obx.QueryIntegerProperty<AppSetting>(
    _entities[0].properties[14],
  );

  /// See [AppSetting.fontColor].
  static final fontColor = obx.QueryStringProperty<AppSetting>(
    _entities[0].properties[15],
  );

  /// See [AppSetting.windowWidth].
  static final windowWidth = obx.QueryDoubleProperty<AppSetting>(
    _entities[0].properties[16],
  );

  /// See [AppSetting.windowHeight].
  static final windowHeight = obx.QueryDoubleProperty<AppSetting>(
    _entities[0].properties[17],
  );

  /// See [AppSetting.isMaximized].
  static final isMaximized = obx.QueryBooleanProperty<AppSetting>(
    _entities[0].properties[18],
  );

  /// See [AppSetting.lastOpenedFolder].
  static final lastOpenedFolder = obx.QueryStringProperty<AppSetting>(
    _entities[0].properties[19],
  );

  /// See [AppSetting.recentFolders].
  static final recentFolders = obx.QueryStringVectorProperty<AppSetting>(
    _entities[0].properties[20],
  );

  /// See [AppSetting.createdAt].
  static final createdAt = obx.QueryDateProperty<AppSetting>(
    _entities[0].properties[21],
  );

  /// See [AppSetting.updatedAt].
  static final updatedAt = obx.QueryDateProperty<AppSetting>(
    _entities[0].properties[22],
  );
}
